spring:
  application:
    name: school-management-app
  datasource:
    url: jdbc:postgresql://localhost:5432/school_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

springdoc:
  enable-data-rest: false
  enable-hateoas: false
